swagger: '2.0'
info:
  version: '0.0.1'
  title: Admin Bot
  description: |
     Current functionality:
        Creating developer user on pod, and emailing sign in info.
        Generating and registering bot cert and creating bot service user on pod for developer.
        Generating and registering app cert and creating new app on pod for developer.
        Messaging developer within symphony bootstrap info (Certs and bot/app credentials).
produces:
  - application/json
tags:
  - Service
schemes:
  - http
  - https
basePath: '/adminbot'
paths:
  '/v1/sendDeveloperWelcome':
    post:
      summary: Sends user welcome messages and emails.
      description:
          Creates the users in the pod, as defined within the sign up form.
          App name, description, url, domain, company name are required for creating an app.
          Sends welcome emails with username and temporary password.
          Sends directional welcome message to users, for when they login.
          If auto bootstrap option is set, all developers will also be automatically bootstraped.
      parameters:
        - name: sessionToken
          in: header
          required: true
          type: string
        - name: welcomeDetail
          in: body
          required: true
          schema:
            $ref: '#/definitions/DeveloperWelcomeDetail'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DeveloperWelcomeResponse'
      tags:
        - SignUp
  '/v1/bootstrapDeveloper':
    post:
      summary: Bootstraps a bootstrap.
      description:
          Used to bootstrap users individually.
          If not already created -
            Creates and registers bot cert, creates bot user.
            Creates and registers app cert, creates app.
          Sends bootstrap bootstrap package within symphony to devleoper user.
      parameters:
        - name: sessionToken
          in: header
          required: true
          type: string
        - name: bootstrap
          in: body
          required: true
          schema:
            $ref: '#/definitions/Developer'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/DeveloperBootstrapInfo'
      tags:
        - SignUp

definitions:
  SuccessResponse:
    type: object
    properties:
      message:
        type: string
        default: "OK"
  DeveloperWelcomeDetail:
    description: Full details about developer welcome.
    type: object
    properties:
      signUpForm:
        $ref: '#/definitions/DeveloperSignUpForm'
        required: true
      welcomeSettings:
        $ref: '#/definitions/WelcomeSettings'
  WelcomeSettings:
    type: object
    properties:
      autoBootstrap:
        type: boolean
        description: |
          If true, will automatically bootstrap all developers in sign up form.
          If false, must call bootstrapDeveloper enpoint to indivdually bootstrap developers (when needed).
        default: true
  DeveloperSignUpForm:
    type: object
    properties:
      creator:
        $ref: '#/definitions/Developer'
      team:
        type: array
        items:
          $ref: '#/definitions/Developer'
      appId:
        type: string
        description: the app id
        required: false
      appName:
        type: string
        description: the app name. Only required for creating app.
        required: false
      appUrl:
        type: string
        description: the app url. Only required for creating app.
        required: false
      appCompanyName:
        type: string
        description: the app company name. Only required for creating app.
        required: false
      appDomain:
        type: string
        description: the app domain. Only required for creating app.
        required: false
      appDescription:
        type: string
        description: the app description. Only required for creating app.
        required: false
      appIconUrl:
        type: string
        description: the app icon url
        required: false
      botName:
        type: string
        description: the bot name
        required: false
      botEmail:
        type: string
        description: the bot email
        required: true
  Developer:
    type: object
    properties:
      firstName:
        type: string
        description: The first name of the developer.
        required: true
      lastName:
        type: string
        description: The last name of the developer.
        required: true
      email:
        type: string
        description: The email of the developer.
        required: true
  DeveloperBootstrapInfo:
    type: object
    properties:
      botUsername:
        type: string
        description: The service user bootstraped onto pod's username.
      botEmail:
        type: string
        description: The service user bootstraped onto pod's email.
      appId:
        type: string
        description: The app bootstraped onto pod's app id.
      appName:
        type: string
        description: The app bootstraped onto pod's app name.
  DeveloperWelcomeResponse:
    description: Response about developer welcome.
    properties:
      message:
        type: string
      bootstrapInfo:
        $ref: '#/definitions/DeveloperBootstrapInfo'
        description: If auto bootstrap was set to true, developer welcome will return bootstrap info.