swagger: '2.0'
info:
  version: '0.0.1'
  title: Admin Bot
  description: |
produces:
  - application/json
tags:
  - Service
schemes:
  - http
  - https
basePath: '/adminbot'
paths:
  '/v1/sendDeveloperWelcome':
    post:
      summary: Sends user welcome messages and emails.
      description:
          Creates the users in the pod, as defined within the sign up form.
          Sends welcome emails with username and temporary password.
          Sends directional welcome message to users, for when they login.
      parameters:
        - name: sessionToken
          in: header
          required: true
          type: string
        - name: keyManagerToken
          in: header
          required: true
          type: string
        - name: signUpForm
          in: body
          required: true
          schema:
            $ref: '#/definitions/DeveloperSignUpForm'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SuccessResponse'
      tags:
        - SignUp
  '/v1/bootstrapDeveloper':
    post:
      summary: Bootstraps a bootstrap.
      description:
          If not already created -
            Creates and registers bot cert, creates bot user.
            Creates and registers app cert, creates app.
          Sends bootstrap bootstrap package within symphony.
      parameters:
        - name: sessionToken
          in: header
          required: true
          type: string
        - name: keyManagerToken
          in: header
          required: true
          type: string
        - name: bootstrap
          in: body
          required: true
          schema:
            $ref: '#/definitions/Developer'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/DeveloperBootstrapInfo'
      tags:
        - SignUp

definitions:
  SuccessResponse:
    type: object
    properties:
      message:
        type: string
        default: "OK"
  DeveloperSignUpForm:
    type: object
    properties:
      creator:
        $ref: '#/definitions/Developer'
      team:
        type: array
        items:
          $ref: '#/definitions/Developer'
      appName:
        type: string
        required: true
      appUrl:
        type: string
        required: true
      appCompanyName:
        type: string
        required: true
      appDomain:
        type: string
        required: true
      appDescription:
        type: string
        required: true
      botName:
        type: string
        required: true
      botEmail:
        type: string
        required: true
      appIconUrl:
        type: string
        required: false
  Developer:
    type: object
    properties:
      firstName:
        type: string
        required: true
      lastName:
        type: string
        required: true
      email:
        type: string
        required: true
  DeveloperBootstrapInfo:
    type: object
    properties:
      botUsername:
        type: string
      botEmail:
        type: string
      appId:
        type: string
      appName:
        type: string